=== RubenMT1999/proyecto_xml/esquemas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">



<xs:element name="altura" type="xs:decimal"/>
<xs:element name="peso" type="xs:decimal"/>
<xs:element name="categoria" type="xs:string"/>
<xs:element name="habilidad" type="xs:string"/>

<xs:element name="sexo">
   <xs:simpleType>
      <xs:restriction base="xs:string">
          <xs:enumeration value="M"/>
          <xs:enumeration value="F"/>
          <xs:enumeration value="I"/>
      </xs:restriction>
   </xs:simpleType>
</xs:element>




<xs:element name="descripcion" type="xs:string"/>
<xs:element name="descripciondebilidad" type="xs:string"/>
<xs:element name="efectividad" type="xs:string"/>
<xs:element name="descripcionfortaleza" type="xs:string"/>
<xs:element name="efectividaddos" type="xs:string"/>



<xs:element name="ps">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>

 <xs:element name="at">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>


 <xs:element name="def">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>

 <xs:element name="spat">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>

 <xs:element name="spde">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>

 <xs:element name="vel">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="255" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>



<xs:element name="tiene_megaevolucion" type="xs:boolean"/>

<xs:element name="orden">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="2" />
            <xs:minInclusive value ="-2" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>

 <xs:element name="num_pokedex">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
 </xs:element>




<!-- Atributos-->

<xs:attribute name="nombre" type="xs:string"/>

<xs:attribute name="num_pokedex">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="generacion">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="8" />
            <xs:minInclusive value ="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="tipo">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="comun"/>
            <xs:enumeration value="starter"/>
            <xs:enumeration value="pseudo_legendario"/>
            <xs:enumeration value="legendario"/>
            <xs:enumeration value="ultra_ente"/>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>


<!-- Elementos Compuestos-->

<xs:element name="datos_generales" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="altura"/>
            <xs:element ref="peso"/>
            <xs:element ref="sexo"/>
            <xs:element ref="categoria"/>
            <xs:element ref="habilidad"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>




 <xs:element name="tipo" >
    <xs:complexType>
        <xs:sequence minOccurs="1" maxOccurs="2">
            <xs:element ref="descripcion"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="tipos" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="tipo"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>


 <xs:element name="tipodebilidad" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="descripciondebilidad"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="debilidad" >
    <xs:complexType>
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="tipodebilidad"/>
            <xs:element ref="efectividad"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="debilidades" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="debilidad"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="tipofortaleza" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="descripcionfortaleza"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="fortaleza" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="tipofortaleza"/>
            <xs:element ref="efectividaddos"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="fortalezas" >
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="fortaleza"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="tipologia">
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="tipos"/>
            <xs:element ref="debilidades"/>
            <xs:element ref="fortalezas"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>





 <xs:element name="stats_base">
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="ps"/>
            <xs:element ref="at"/>
            <xs:element ref="def"/>
            <xs:element ref="spat"/>
            <xs:element ref="spde"/>
            <xs:element ref="vel"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>





 <xs:element name="evolucion">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="orden"/>
            <xs:element ref="num_pokedex"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>

 <xs:element name="evoluciones">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="tiene_megaevolucion"/>
            <xs:element ref="evolucion"/>
        </xs:sequence>
    </xs:complexType>
 </xs:element>



 <xs:element name="pokemon">
    <xs:complexType>
        <xs:sequence minOccurs="1">
            <xs:element ref="datos_generales"/>
            <xs:element ref="tipologia"/>
            <xs:element ref="stats_base"/>
            <xs:element ref="evoluciones"/>
        </xs:sequence>
            <xs:attribute ref="nombre"/>
            <xs:attribute ref="num_pokedex"/>
            <xs:attribute ref="generacion"/>
            <xs:attribute ref="tipo"/>
    </xs:complexType>
 </xs:element>

 <xs:element name="pokedex">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="pokemon"/>    
        </xs:sequence>
    </xs:complexType>
 </xs:element>
 


</xs:schema>

=== RubenMT1999/proyecto_xml/pokedex.xml
<?xml version="1.0" encoding="UTF-8"?>



<!-- <!DOCTYPE pokedex SYSTEM "implementacion.dtd">-->

<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemas.xsd"-->

<pokedex >
    <pokemon nombre= "bulbasur" num_pokedex= "1" generacion="1" tipo= "starter" url_imagen="https://tecmoviles.com/wp-content/uploads/2016/09/evolucion-de-bulbasaur-todos-los-trucos-bulbasaur-600x600.png">

        <datos_generales>
            <altura>0.45</altura>
            <peso>20.00</peso>
            <sexo>M</sexo>
            <categoria>semilla</categoria>
            <habilidad>espesura</habilidad>
        </datos_generales>

        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>planta</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipodebilidad>
                        <descripciondebilidad>fuego</descripciondebilidad>
                    </tipodebilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipofortaleza>
                        <descripcionfortaleza>agua</descripcionfortaleza>
                    </tipofortaleza>
                    <efectividaddos>x2</efectividaddos>
                </fortaleza>
            </fortalezas>
        </tipologia>

        <stats_base>
            <ps>30</ps>
            <at>10</at>
            <def>12</def>
            <spat>15</spat>
            <spde>13</spde>
            <vel>5</vel>
        </stats_base>

        <evoluciones>
            <tiene_megaevolucion>true</tiene_megaevolucion>
            <evolucion>
                <orden>-1</orden>
                <num_pokedex>2</num_pokedex>
            </evolucion>
        </evoluciones>

    </pokemon>

    <pokemon nombre= "houndour" num_pokedex= "8" generacion="2" tipo= "pseudo-legendario" url_imagen="https://static.wikia.nocookie.net/espokemon/images/b/ba/Houndour.png/revision/latest?cb=20140210190419">

        <datos_generales>
            <altura>0.6</altura>
            <peso>10.15</peso>
            <sexo>M</sexo>
            <categoria>fuego</categoria>
            <categoria>siniestro</categoria>
            <habilidad>absorbe fuego</habilidad>
            <habilidad>madrugar</habilidad>
        </datos_generales>

        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>fuego</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipodebilidad>
                        <descripciondebilidad>agua</descripciondebilidad>
                    </tipodebilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipofortaleza>
                        <descripcionfortaleza>planta</descripcionfortaleza>
                    </tipofortaleza>
                    <efectividaddos>x3</efectividaddos>
                </fortaleza>
            </fortalezas>
        </tipologia>

        <stats_base>
            <ps>70</ps>
            <at>30</at>
            <def>25</def>
            <spat>25</spat>
            <spde>30</spde>
            <vel>10</vel>
        </stats_base>

        <evoluciones>
            <tiene_megaevolucion>false</tiene_megaevolucion>
            <evolucion>
                <orden>1</orden>
                <num_pokedex>49</num_pokedex>
            </evolucion>
        </evoluciones>

    </pokemon>



    <pokemon nombre= "snorlax" num_pokedex= "21" generacion="1" tipo= "comun" url_imagen="https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1339720808571285506%2FrduevdF8_400x400.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fmunchlax_x&tbnid=rA90VODd3Wnk7M&vet=10CNYBEDMowAFqFwoTCJClgI6cqvYCFQAAAAAdAAAAABAC..i&docid=910dbDfsfx-jwM&w=400&h=400&q=snorlax&ved=0CNYBEDMowAFqFwoTCJClgI6cqvYCFQAAAAAdAAAAABAC#imgrc=BZmcV9nkYmAjSM&imgdii=-VwMcRwMjvVm1M">

        <datos_generales>
            <altura>0.8</altura>
            <peso>300</peso>
            <sexo>M</sexo>
            <categoria>luchador</categoria>
            <categoria>tierra</categoria>
            <habilidad>aplastar</habilidad>
            <habilidad>madrugar</habilidad>
        </datos_generales>

        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>luchador</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipodebilidad>
                        <descripciondebilidad>fuego</descripciondebilidad>
                    </tipodebilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipofortaleza>
                        <descripcionfortaleza>planta</descripcionfortaleza>
                    </tipofortaleza>
                    <efectividaddos>x3</efectividaddos>
                </fortaleza>
            </fortalezas>
        </tipologia>

        <stats_base>
            <ps>150</ps>
            <at>40</at>
            <def>85</def>
            <spat>35</spat>
            <spde>20</spde>
            <vel>10</vel>
        </stats_base>

        <evoluciones>
            <tiene_megaevolucion>false</tiene_megaevolucion>
            <evolucion>
                <orden>1</orden>
                <num_pokedex>21</num_pokedex>
            </evolucion>
        </evoluciones>

    </pokemon>

    <pokemon nombre= "pikachu" num_pokedex= "1" generacion="1" tipo= "starter" url_imagen="https://www.google.com/imgres?imgurl=https%3A%2F%2Fassets.pokemon.com%2Fassets%2Fcms2%2Fimg%2Fwatch-pokemon-tv%2Fseasons%2Fseason23%2Fseason23_ep01_ss04.jpg&imgrefurl=https%3A%2F%2Fwww.pokemon.com%2Fel%2Fepisodios-pokemon%2F23_01-presentando-a-pikachu%2F&tbnid=d_RNA6k7FDKG_M&vet=12ahUKEwjPjPjAnKr2AhW9QkEAHewPAWcQMygnegUIARCxAg..i&docid=V-5VhN4q4OA9oM&w=578&h=327&q=pikachu&ved=2ahUKEwjPjPjAnKr2AhW9QkEAHewPAWcQMygnegUIARCxAg">

        <datos_generales>
            <altura>0.6</altura>
            <peso>8.15</peso>
            <sexo>M</sexo>
            <categoria>electrico</categoria>
            <habilidad>impactrueno</habilidad>
            <habilidad>cola ferrea</habilidad>
        </datos_generales>

        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>rayo</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipodebilidad>
                        <descripciondebilidad>fuego</descripciondebilidad>
                    </tipodebilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipofortaleza>
                        <descripcionfortaleza>agua</descripcionfortaleza>
                    </tipofortaleza>
                    <efectividaddos>x3</efectividaddos>
                </fortaleza>
            </fortalezas>
        </tipologia>

        <stats_base>
            <ps>75</ps>
            <at>40</at>
            <def>25</def>
            <spat>35</spat>
            <spde>30</spde>
            <vel>30</vel>
        </stats_base>

        <evoluciones>
            <tiene_megaevolucion>false</tiene_megaevolucion>
            <evolucion>
                <orden>1</orden>
                <num_pokedex>1</num_pokedex>
            </evolucion>
        </evoluciones>

    </pokemon>


    <pokemon nombre= "charizard" num_pokedex= "35" generacion="1" tipo= "pseudo-legendario" url_imagen="https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fespokemon%2Fimages%2Fc%2Fcf%2FCharizard_de_Rojo_PO.png%2Frevision%2Flatest%3Fcb%3D20180315025050&imgrefurl=https%3A%2F%2Fpokemon.fandom.com%2Fes%2Fwiki%2FCharizard_de_Rojo&tbnid=lLJARQ6XE3_IHM&vet=12ahUKEwi1ufnYnKr2AhXRlFwKHah8DGIQMyhBegQIARB9..i&docid=4mD7SAcwjgWRHM&w=1566&h=881&q=charizard&ved=2ahUKEwi1ufnYnKr2AhXRlFwKHah8DGIQMyhBegQIARB9">

        <datos_generales>
            <altura>2</altura>
            <peso>57</peso>
            <sexo>M</sexo>
            <categoria>fuego</categoria>
            <categoria>dragon</categoria>
            <habilidad>absorbe fuego</habilidad>
            <habilidad>vuelo</habilidad>
        </datos_generales>

        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>fuego</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipodebilidad>
                        <descripciondebilidad>agua</descripciondebilidad>
                    </tipodebilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipofortaleza>
                        <descripcionfortaleza>planta</descripcionfortaleza>
                    </tipofortaleza>
                    <efectividaddos>x3</efectividaddos>
                </fortaleza>
            </fortalezas>
        </tipologia>

        <stats_base>
            <ps>90</ps>
            <at>50</at>
            <def>65</def>
            <spat>55</spat>
            <spde>40</spde>
            <vel>30</vel>
        </stats_base>

        <evoluciones>
            <tiene_megaevolucion>true</tiene_megaevolucion>
            <evolucion>
                <orden>1</orden>
                <num_pokedex>35</num_pokedex>
            </evolucion>
        </evoluciones>

    </pokemon>
